"use client";

import Link from "next/link";
import { useEffect,useState } from "react";
import { getServices,type ServiceRecord } from "@/lib/firebase/data";

export default function TreatmentsPage(){
 const [services,setServices]=useState<ServiceRecord[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{void getServices().then(items=>setServices(items.filter(x=>x.active))).catch(()=>setServices([])).finally(()=>setLoading(false));},[]);
 const grouped=services.reduce<Record<string,ServiceRecord[]>>((acc,item)=>(acc[item.category]??=[],acc[item.category].push(item),acc),{});
 return <main className="site"><nav className="nav"><div className="container navInner"><Link href="/" className="brand"><span className="brandMark">S</span><span>TRIPPLE S<span>WELLNESS SPA</span></span></Link><Link href="/book" className="button buttonPrimary">Book an appointment</Link></div></nav><section className="section"><div className="container"><div className="sectionHead"><span className="kicker">Treatments & pricing</span><h1>Find the care that fits your goal.</h1><p>Prices are shown in Botswana Pula and may vary after clinical assessment. Suitability is determined by the Tripple S clinical team.</p></div>{loading?<div className="loadingCard">Opening the treatment catalogue…</div>:services.length===0?<div className="emptyPublic"><h3>The treatment catalogue is not published yet.</h3><p>Start with a consultation and the team can guide you.</p><Link href="/book?service=skin-consultation" className="button buttonPrimary">Book a consultation</Link></div>:Object.entries(grouped).map(([category,items])=><section key={category} style={{marginBottom:55}}><div className="sectionHead"><span className="kicker">{category}</span></div><div className="serviceGrid">{items.map(item=><article className="serviceCard" key={item.id}><span>{item.duration}</span><h3>{item.name}</h3><p>{item.description}</p>{item.assessmentNote&&<p><strong>{item.assessmentNote}</strong></p>}<div className="serviceMeta"><strong>{item.price}</strong><small>{item.consultationRequired?"Assessment may be required":"Appointment request"}</small></div><Link href={`/book?service=${encodeURIComponent(item.id)}`} className="button buttonDark">Request appointment</Link></article>)}</div></section>)}</div></section><section className="confidence"><div className="container confidenceGrid"><div><span className="kicker">Not sure?</span><h2>Tell us what you want to improve.</h2><p>You do not need to diagnose yourself or choose the perfect treatment before speaking with the team.</p></div><Link href="/book?service=skin-consultation" className="button buttonLight">Book a consultation</Link></div></section></main>;
}